name: skribble
version: 0.2.0
publish_to: none

environment:
  sdk: ^3.11.0
  flutter: ^3.41.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.3
  google_fonts: ^8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  skribble_lints:
    path: ../skribble_lints

flutter:
  uses-material-design: true
