import 'package:flutter/material.dart';
import 'package:flutter_hooks/flutter_hooks.dart';

import 'motion/wired_ink_interaction.dart';
import 'motion/wired_motion.dart';
import 'rough/skribble_rough.dart';
import 'wired_roughness.dart';

/// The default hand-drawn font family bundled with Skribble.
///
/// Based on Recursive Casual with gently warped TrueType outlines.
/// Generated by the Dart writer in `packages/skribble_font_roughen`.
const String skribbleFontFamily = 'SkribbleGentle';

/// Theme data for Wired widgets.
class WiredThemeData {
  /// Whether decorative ink motion is permitted. Reduced motion still wins.
  final bool motionEnabled;

  /// Default decorative feedback for buttons in this theme.
  final WiredInkInteraction inkInteraction;

  final Color borderColor;
  final Color textColor;
  final Color disabledTextColor;
  final Color fillColor;
  final double strokeWidth;
  final DrawConfig? _drawConfig;

  /// Coordinated border and font settings. Defaults to gentle ink.
  final WiredRoughness roughnessLevel;
  final double? _roughness;
  final String? _fontFamily;

  /// Geometry amplitude; an explicit constructor value overrides the level.
  double get roughness => _roughness ?? roughnessLevel.roughness;

  /// Font family; an explicit constructor value overrides the level.
  String get fontFamily => _fontFamily ?? roughnessLevel.fontFamily;

  /// Asset package for bundled fonts, or null for an app-provided family.
  String? get fontPackage =>
      WiredRoughness.values.any(
        (level) => level.fontFamily == fontFamily,
      )
      ? 'skribble'
      : null;

  WiredThemeData({
    this.motionEnabled = true,
    this.inkInteraction = WiredInkInteraction.pressure,
    this.borderColor = const Color(0xFF1A2B3C),
    this.textColor = Colors.black,
    this.disabledTextColor = Colors.grey,
    this.fillColor = const Color(0xFFFEFEFE),
    this.strokeWidth = 2.4,
    this.roughnessLevel = WiredRoughness.gentle,
    this._roughness,
    this._fontFamily,
    this._drawConfig,
  });

  DrawConfig get drawConfig =>
      _drawConfig ??
      DrawConfig.build(
        roughness: roughness,
        maxRandomnessOffset: roughnessLevel.maxRandomnessOffset,
        lineWobble: roughnessLevel.lineWobble,
      );

  static final defaultTheme = WiredThemeData();

  WiredThemeData copyWith({
    bool? motionEnabled,
    WiredInkInteraction? inkInteraction,
    Color? borderColor,
    Color? textColor,
    Color? disabledTextColor,
    Color? fillColor,
    double? strokeWidth,
    DrawConfig? drawConfig,
    double? roughness,
    String? fontFamily,
    WiredRoughness? roughnessLevel,
  }) {
    return WiredThemeData(
      motionEnabled: motionEnabled ?? this.motionEnabled,
      inkInteraction: inkInteraction ?? this.inkInteraction,
      borderColor: borderColor ?? this.borderColor,
      textColor: textColor ?? this.textColor,
      disabledTextColor: disabledTextColor ?? this.disabledTextColor,
      fillColor: fillColor ?? this.fillColor,
      strokeWidth: strokeWidth ?? this.strokeWidth,
      drawConfig: drawConfig ?? _drawConfig,
      roughnessLevel: roughnessLevel ?? this.roughnessLevel,
      roughness: roughness ?? _roughness,
      fontFamily: fontFamily ?? _fontFamily,
    );
  }

  /// Space required by a divider's pen, wobble, and anti-aliased edges.
  double get inkExtent =>
      strokeWidth +
      2 +
      (drawConfig.maxRandomnessOffset ?? 2) * (drawConfig.roughness ?? 1.8) * 2;

  /// A softly lifted paper tone for Material page backgrounds.
  Color get paperBackgroundColor =>
      Color.alphaBlend(fillColor.withValues(alpha: 0.92), Colors.white);

  /// Builds a Material [ColorScheme] from Skribble theme colors.
  ColorScheme toColorScheme({Brightness brightness = Brightness.light}) {
    final base = ColorScheme.fromSeed(
      seedColor: borderColor,
      brightness: brightness,
      surface: fillColor,
    );

    return base.copyWith(
      primary: borderColor,
      onPrimary: _bestContrastingColor(borderColor),
      secondary: textColor,
      onSecondary: _bestContrastingColor(textColor),
      surface: fillColor,
      onSurface: textColor,
      outline: borderColor.withValues(alpha: 0.7),
      surfaceTint: borderColor,
      shadow: borderColor.withValues(alpha: 0.12),
    );
  }

  /// Builds a Material [ThemeData] aligned with the active Skribble palette.
  ThemeData toThemeData({
    Brightness brightness = Brightness.light,
    bool useMaterial3 = true,
    TextTheme? textTheme,
  }) {
    final colorScheme = toColorScheme(brightness: brightness);
    final baseTextTheme =
        textTheme ??
        ThemeData(brightness: brightness, useMaterial3: useMaterial3).textTheme;
    final themedTextTheme = baseTextTheme
        .apply(
          fontFamily: fontFamily,
          package: fontPackage,
        )
        .apply(bodyColor: textColor, displayColor: textColor);

    return ThemeData(
      brightness: brightness,
      useMaterial3: useMaterial3,
      colorScheme: colorScheme,
      fontFamily: fontFamily,
      package: fontPackage,
      scaffoldBackgroundColor: paperBackgroundColor,
      canvasColor: fillColor,
      dividerColor: borderColor.withValues(alpha: 0.35),
      textTheme: themedTextTheme,
      iconTheme: IconThemeData(color: textColor),
      primaryIconTheme: IconThemeData(color: colorScheme.onPrimary),
      appBarTheme: AppBarTheme(
        backgroundColor: paperBackgroundColor,
        foregroundColor: textColor,
        elevation: 0,
        shadowColor: Colors.transparent,
        surfaceTintColor: Colors.transparent,
      ),
      cardTheme: CardThemeData(
        color: fillColor,
        elevation: 0,
        surfaceTintColor: Colors.transparent,
        margin: EdgeInsets.zero,
      ),
      bottomSheetTheme: BottomSheetThemeData(
        backgroundColor: fillColor,
        surfaceTintColor: Colors.transparent,
        elevation: 0,
      ),
      dialogTheme: DialogThemeData(
        backgroundColor: fillColor,
        surfaceTintColor: Colors.transparent,
        elevation: 0,
      ),
      dividerTheme: DividerThemeData(
        color: borderColor.withValues(alpha: 0.35),
        thickness: 1,
      ),
      snackBarTheme: SnackBarThemeData(
        backgroundColor: fillColor,
        contentTextStyle: TextStyle(color: textColor),
        actionTextColor: borderColor,
      ),
      inputDecorationTheme: InputDecorationTheme(
        filled: true,
        fillColor: fillColor,
        border: OutlineInputBorder(
          borderRadius: BorderRadius.circular(16),
          borderSide: BorderSide(color: borderColor, width: strokeWidth),
        ),
        enabledBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(16),
          borderSide: BorderSide(color: borderColor, width: strokeWidth),
        ),
        focusedBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(16),
          borderSide: BorderSide(color: borderColor, width: strokeWidth + 0.5),
        ),
      ),
    );
  }
}

Color _bestContrastingColor(Color color) {
  return ThemeData.estimateBrightnessForColor(color) == Brightness.dark
      ? Colors.white
      : Colors.black;
}

/// Cascades geometry, ink colors, and typography to descendant Wired widgets.
///
/// Use `WiredMaterialApp` at the app root. A nested [WiredTheme] can override
/// a section; use `WiredTheme.of(context).copyWith(roughnessLevel: ...)` to
/// retain the surrounding palette. Explicit font and geometry overrides are
/// preserved by `copyWith`, including when changing levels.
class WiredTheme extends HookWidget {
  /// Creates a theme boundary without rebuilding its child's local state.
  const WiredTheme({super.key, required this.data, required this.child});

  /// The resolved theme for this subtree.
  final WiredThemeData data;

  /// The subtree that inherits this theme.
  final Widget child;

  /// Returns the nearest Wired theme, or the gentle default.
  static WiredThemeData of(BuildContext context) =>
      context.dependOnInheritedWidgetOfExactType<_WiredThemeScope>()?.data ??
      WiredThemeData.defaultTheme;

  @override
  Widget build(BuildContext context) {
    // The compatibility bridge updates Material text styles as well as plain
    // Text, so local font overrides reach existing Material-backed controls.
    final parent = Theme.of(context);
    TextTheme apply(TextTheme value) => value.apply(
      fontFamily: data.fontFamily,
      package: data.fontPackage,
      bodyColor: data.textColor,
      displayColor: data.textColor,
    );
    return _WiredThemeScope(
      data: data,
      child: Theme(
        data: parent.copyWith(
          textTheme: apply(parent.textTheme),
          primaryTextTheme: apply(parent.primaryTextTheme),
        ),
        child: DefaultTextStyle.merge(
          style: TextStyle(
            fontFamily: data.fontFamily,
            package: data.fontPackage,
            color: data.textColor,
          ),
          child: WiredMotion(enabled: data.motionEnabled, child: child),
        ),
      ),
    );
  }
}

class _WiredThemeScope extends InheritedTheme {
  const _WiredThemeScope({required this.data, required super.child});
  final WiredThemeData data;

  @override
  Widget wrap(BuildContext context, Widget child) =>
      WiredTheme(data: data, child: child);

  @override
  bool updateShouldNotify(_WiredThemeScope oldWidget) => data != oldWidget.data;
}
